---
- name: Instalar mysql
  dnf: name=myqsl-server state=present

- name: Configurar Mysql
  template: src=my.cnf dest=/etc/my.conf
  notify: restart mysql

- name: Iniciar Mysql
  service: name=mysqld state=started enabled=yes
