---
- name: Instalar Tomcat
  dnf: name=tomcat state=present

#- name: Configurar Mysql
#  template: src=my.cnf dest=/etc/my.conf
#  notify: restart tomcat

- name: Iniciar Tomcat
  service: name=tomcat state=started enabled=yes
