---
- name: Instalar mysql
  dnf: name=mariadb-server state=present

#- name: Configurar Mysql
#  template: src=my.cnf dest=/etc/my.conf
#  notify: restart mariadb

- name: Iniciar Mysql
  service: name=mariadb state=started enabled=yes
