---
- name: Instalar Tomcat
  dnf: name={{ item }} state=present
  with_items:
    - tomcat
    - tomcat-webapps
    - tomcat-docs-webapp
    - tomcat-admin-webapps

- name: Configurar Tomcat
  template: src=tomcat-users.xml dest=/etc/tomcat/tomcat-users.xml user=root group=tomcat
  notify: restart tomcat

- name: Iniciar Tomcat
  service: name=tomcat state=started enabled=yes
