---
- name: Instalar Tomcat
  dnf: name={{ item }} state=present
  with_items:
    - tomcat
    - tomcat-webapps
    - tomcat-docs-webapps
    - tomcat-admin-webapps

#- name: Configurar Tomcat
#  template: src=my.cnf dest=/etc/my.conf
#  notify: restart tomcat

- name: Iniciar Tomcat
  service: name=tomcat state=started enabled=yes
