---
- name: Configurar Firewall http
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
- name: Configurar Firewall https
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
- name: Detener provisionalmente
  ansible.builtin.service: 
    name: firewalld
    state: stopped
    enabled: no