---
- name: Instalar servidor PHP FPM y dependencias
  dnf: name={{ item }} state=present
  with_items:
    - php
    - php-fpm
    - php-xml
    - php-process
    - php-mysqlnd
    - php-mbstring

- name: Desactivar pila por defecto
  command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled
  notify: restart php-fpm

- name: Copiar configuración de PHP
  template: src=project.conf dest=/etc/php-fpm.d/
  notify: restart php-fpm

- name: Cargar configuración
  copy: src=phpinfo.php dest=/var/www/html/
  notify: restart nginx